server:
  port: 8777

spring:
  application:
    name: hazelcast-kubernetes
  datasource:
    url: jdbc:h2:file:./target/db/hazelcast;
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

cache:
  client:
    cluster-name: sbe-cache
    hosts: 127.0.0.1:5701,127.0.0.1:5702,127.0.0.1:5703
    connection-timeout: 3000

---
spring:
  config:
    name: kubernetes
    activate:
      on-profile: kubernetes
cache:
  client:
    hosts: sbe-hazelcast
  kubernetes:
    enabled: true
    namespace: default
    service-name: sbe-hazelcast


#---
#spring:
#  config:
#    name: docker
#    activate:
#      on-profile: docker
#
#cache:
#  client:
#    hosts: sbe-hazelcast:5701,sbe-hazelcast-2:5701,sbe-hazelcast-3:5703

