version: "3.9"

networks:
  sbe-network:
    name: sbe-network

services:
  sbe-hazelcast:
    image: hazelcast/hazelcast:latest
    container_name: sbe-hazelcast
    restart: unless-stopped
    networks:
      - sbe-network
    environment:
      HZ_CLUSTERNAME: sbe-cache
      HZ_NETWORK_PORT_PORT: 5701
      HZ_NETWORK_PUBLICADDRESS: sbe-hazelcast:5701

  sbe-hazelcast-2:
    image: hazelcast/hazelcast:latest
    container_name: sbe-hazelcast-2
    restart: unless-stopped
    networks:
      - sbe-network
    environment:
      HZ_CLUSTERNAME: sbe-cache
      HZ_NETWORK_PORT_PORT: 5701
      HZ_NETWORK_PUBLICADDRESS: sbe-hazelcast-2:5701

  sbe-hazelcast-3:
    image: hazelcast/hazelcast:latest
    container_name: sbe-hazelcast-3
    restart: unless-stopped
    networks:
      - sbe-network
    environment:
      HZ_CLUSTERNAME: sbe-cache
      HZ_NETWORK_PORT_PORT: 5701
      HZ_NETWORK_PUBLICADDRESS: sbe-hazelcast-3:5701

  sbe-hc-mgmt:
    image: hazelcast/management-center:5.1.3
    container_name: sbe-hc-mgmt
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - sbe-network
    environment:
      - MC_ADMIN_USER=admin
      - MC_ADMIN_PASSWORD=hazelcast01
      - MC_DEFAULT_CLUSTER=sbe-cache
      - MC_DEFAULT_CLUSTER_MEMBERS=sbe-hazelcast

  hc-kub:
    image: techtabu/sbe/hazelcast-kubernetes
    container_name: hc-kub
    restart: unless-stopped
    ports:
      - "8777:8777"
    networks:
      - sbe-network
    environment:
      CACHE_CLIENT_HOSTS: sbe-hazelcast

