
spring:
  application:
    name: embedded-hazelcast

cache:
  cluster-name: sbe-cache
  kubernetes:
    discovery:
      method: DNS_LOOKUP
    namespace: default
    service-name: sbe-hazelcast
    service-dns: ${cache.kubernetes.service-name}.${cache.kubernetes.namespace}.svc.cluster.local
  diagnostic:
    enabled: true


