server:
  port: 9771

spring:
  application:
    name: tabu-springboot-kafka
  kafka:
    bootstrap-servers: localhost:9093
    streams:
      application-id: ${spring.application.name}
    consumer:
      group-id: "kafka-group"
      client-id: ${spring.application.name}_consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      concurrency: 2
      ack-mode: RECORD
    admin:
      client-id: ${spring.application.name}_admin


---
spring:
  config:
    name: ssl
    activate:
      on-profile: ssl
  kafka:
    ssl:
      trust-store-location: classpath:certs/kafka.truststore.jks
      trust-store-password: deadface11
      key-store-location: classpath:certs/kafka.keystore.jks
      key-store-password: deadface11
      key-password: deadface11
    properties:
      ssl.endpoint.identification.algorithm:
      security.protocol: SSL

---
spring:
  config:
    name: sasl-ssl
    activate.on-profile: sasl-ssl
  kafka:
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: 'GSSAPI'
      sasl.kerberos.service.name: kafka
      sasl.jaas.config: 'com.sun.security.auth.module.Krb5LoginModule required useKeyTab=true storeKey=true keyTab="/home/hpo7955/CorpSvc_Capsule.keytab" principal="CorpSvc_Capsule@HCA.CORPAD.NET";'



