version: "3.9"

services:
  mongo-simple:
    image: mongo:5.0
    container_name: mongo-simple
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: mongodb
