kind: Deployment
apiVersion: apps/v1
metadata:
  name: sbe-hazelcast
  labels:
    app: sbe-hazelcast
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sbe-hazelcast
  template:
    metadata:
      labels:
        app: sbe-hazelcast
    spec:
      containers:
        - name: sbe-hazelcast
          image: hazelcast/hazelcast:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5701
          env:
            - name: HZ_CLUSTERNAME
              value: sbe-cache
            - name: HZ_NETWORK_PORT_PORT
              value: "5701"
#            - name: HZ_NETWORK_PUBLICADDRESS
#              value: sbe-hazelcast:5701
---
apiVersion: v1
kind: Service
metadata:
  name: sbe-hazelcast
  labels:
    app: sbe-hazelcast
spec:
  type: ClusterIP
  ports:
    - name: hz
      port: 5701
      protocol: TCP
  selector:
    app: sbe-hazelcast