apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: monitoring
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'kubernetes-nodes'
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - target_label: __address__
            replacement: kubernetes.default.svc:443
          - source_labels: [__meta_kubernetes_node_name]
            regex: (.+)
            target_label: __metrics_path__
            replacement: /api/v1/nodes/${1}/proxy/metrics
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      - job_name: 'node-exporter'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
        - action: keep
          regex: true
          source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
      - job_name: 'monitoring-ns-pods'
        metrics_path: '/actuator/prometheus'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - monitoring
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: metrics
        - source_labels: [ '__meta_kubernetes_pod_annotation_prometheus_io_path' ]
          regex: '(.*)'
          target_label: '__metrics_path__'
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: "pod_name"
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: "namespace"
        - source_labels: [__meta_kubernetes_pod_ip]
          action: replace
          target_label: "pod_ip"
        - source_labels: [__meta_kubernetes_pod_node_name]
          action: replace
          target_label: "node_name"
