apiVersion: v1
kind: Service
metadata:
  name: spring-boot-prometheus
  namespace: monitoring
  labels:
    app: spring-boot-prometheus
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '9090'
spec:
  type: NodePort
  selector:
    app: spring-boot-prometheus
  ports:
    - port: 9700
      targetPort: 9700
      nodePort: 32000
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: spring-boot-prometheus
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-prometheus
  template:
    metadata:
      labels:
        app: spring-boot-prometheus
      annotations:
        prometheus.io/scrape: "metrics"
        prometheus.io/port: "9700"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: spring-boot-prometheus
          image: techtabu/sbe/spring-boot-prometheus:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9700