server:
  port: 9700

spring:
  application:
    name: sbe-prometheus

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}

