kind: Deployment
apiVersion: apps/v1
metadata:
  name: hc-kub
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hc-kub
  template:
    metadata:
      labels:
        app: hc-kub
    spec:
      containers:
        - name: hc-kub
          image: techtabu/sbe/hazelcast-kubernetes:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8777
          env:
            - name: CACHE_CLIENT_HOSTS
              value: sbe-hazelcast.hazelcast
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
---
apiVersion: v1
kind: Service
metadata:
  name: hc-kub
  namespace: default
  labels:
    app: hc-kub
spec:
  type: NodePort
  ports:
    - name: hz
      port: 8777
      targetPort: 8777
      nodePort: 32000
      protocol: TCP
  selector:
    app: hc-kub