kind: Deployment
apiVersion: apps/v1
metadata:
  name: sbe-hc-mgmt
  namespace: hazelcast
  labels:
    app: sbe-hc-mgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sbe-hc-mgmt
  template:
    metadata:
      labels:
        app: sbe-hc-mgmt
    spec:
      containers:
        - name: sbe-hc-mgmt
          image: hazelcast/management-center:5.1.3
          ports:
            - containerPort: 8080
          env:
            - name: MC_ADMIN_USER
              value: admin
            - name: MC_ADMIN_PASSWORD
              value: hazelcast01
            - name: MC_DEFAULT_CLUSTER
              value: sbe-cache
            - name: MC_DEFAULT_CLUSTER_MEMBERS
              value: sbe-hazelcast
---
apiVersion: v1
kind: Service
metadata:
  name: sbe-hc-mgmt
  namespace: hazelcast
  labels:
    app: sbe-hc-mgmt
spec:
  type: NodePort
  ports:
    - name: hz
      port: 8080
      targetPort: 8080
      nodePort: 31000
      protocol: TCP
  selector:
    app: sbe-hc-mgmt