server:
  port: 9770

spring:
  application:
    name: tabu-springboot-kafka
  kafka:
    bootstrap-servers: localhost:9092
    streams:
      application-id: ${spring.application.name}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      concurrency: 1
      ack-mode: RECORD
  sleuth:
    enabled: false
    otel:
      config:
        trace-id-ratio-based: 1.0
      exporter:
        otlp:
          enabled: true
          endpoint: http://localhost:4317
    baggage:
      tag-fields: ${spring.application.name}
